# Generated by Django 5.2 on 2025-04-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
    ]
