# Generated by Django 5.2 on 2025-04-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvrow',
            name='age',
        ),
        migrations.RemoveField(
            model_name='csvrow',
            name='name',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvrow',
            name='data',
            field=models.JSONField(default='Untitled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvrow',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='csv_uploads/'),
        ),
    ]
