# Generated by Django 5.2 on 2025-04-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0004_remove_csvrow_age_remove_csvrow_name_csvfile_columns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'CSV File', 'verbose_name_plural': 'CSV Files'},
        ),
        migrations.AlterModelOptions(
            name='csvrow',
            options={'ordering': ['row_number']},
        ),
        migrations.AddIndex(
            model_name='csvrow',
            index=models.Index(fields=['csv_file'], name='cworker_csv_csv_fil_9cf3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='csvrow',
            index=models.Index(fields=['row_number'], name='cworker_csv_row_num_d91a54_idx'),
        ),
        migrations.AlterModelTable(
            name='csvfile',
            table='cworker_csvfile',
        ),
        migrations.AlterModelTable(
            name='csvrow',
            table='cworker_csvrow',
        ),
    ]
