# Generated by Django 5.2 on 2025-04-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0005_alter_csvfile_options_alter_csvrow_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCsvRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='csvrow',
            name='csv_file',
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.DeleteModel(
            name='CSVRow',
        ),
    ]
