# Generated by Django 5.2 on 2025-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0006_genericcsvrecord_remove_csvrow_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcsvrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name='genericcsvrecord',
            index=models.Index(fields=['task_id'], name='cworker_gen_task_id_4763ae_idx'),
        ),
    ]
