# Generated by Django 5.2 on 2025-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cworker', '0007_genericcsvrecord_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcsvrecord',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
